name: Secure Code Scan

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  sast_scans:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: day3

      - name: Run Bandit (Python SAST)
        id: bandit
        run: |
          pip install bandit
          bandit -r . -f html -o bandit-report.html || true
        working-directory: day3
        shell: bash
        continue-on-error: true

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: day3/bandit-report.html

      - name: Run Semgrep (Default Behavior)
        id: semgrep
        run: |
          pip install semgrep
          semgrep --config=auto --json --output=reports/semgrep-report.json || true
        working-directory: day3
        shell: bash
        # uses: returntocorp/semgrep-action@v1
        continue-on-error: true

      - name: Upload Semgrep SARIF Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-json-report
          path: day3/semgrep-report.json

  secrets_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks Directly
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz
          tar -xzf gitleaks_8.18.2_linux_x64.tar.gz
          ./gitleaks detect --source="." --config=".github/gitleaks.toml" --report-path="gitleaks-report.json" --redact || true
        continue-on-error: true

      - name: Upload Gitleaks Report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json

  dast_scan:
    runs-on: ubuntu-latest
    needs: [sast_scans, secrets_scan]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: day3

      - name: Start Flask App
        run: |
          nohup python app.py > app.log 2>&1 &
          echo "Waiting for app to start..."
          sleep 15
          curl --fail http://localhost:5000
        working-directory: day3
        shell: bash

      - name: Show logs on failure
        if: failure()
        run: |
          echo "--- App failed to start. Displaying logs from app.log: ---"
          cat app.log
        working-directory: day3

      - name: Run ZAP Baseline Scan via Docker
        continue-on-error: true
        run: |
          sudo chown 1000:1000 ${{ github.workspace }}
          docker run --rm \
            --add-host=host.docker.internal:host-gateway \
            -v ${{ github.workspace }}:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://host.docker.internal:5000/ \
            -g gen.conf \
            -J report_json.json \
            -w report_md.md \
            -r report_html.html

      - name: Upload ZAP DAST Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-reports
          path: |
            report_json.json
            report_md.md
            report_html.html